# Site settings
title: RockRapids.INFO
email: MarkBruns@MarkBruns.com
description: H O M E ... Health ... Opportunities ... Momentum ... Engagement
twitter_username: MarkBruns
github_username:  RockRapids

# Build settings
markdown: kramdown
