# Site settings
title: 4
email: MarkBruns@MarkBruns.com
description: This is for 4) RockRapids.SHOP, ... the others in this ecosystem of apps are 0) INFO 1) ART, 2) FUN, 3) GUIDE, 5) STORE, 6) WORK, 7) XYZ
twitter_username: MarkBruns
github_username:  RockRapids

# Build settings
markdown: kramdown
